export enum STAFF_TYPES {
    PROVIDER = 'PROVIDER_STAFF',
    NURSEING_STAFF = 'NURSING_STAFF',
    ASSISTANT = 'ASSISTANT_STAFF',
    BUSINESS_MANAGER = 'BUSINESS_MANAGER'
}

// for dispaly staff title
export enum STAFF_TYPE_TITLES {
    PROVIDER = 'Provider',
    NURSEING_STAFF = 'Nursing Staff',
    ASSISTANT = 'Assistant',
    BUSINESS_MANAGER = 'Business Manager'
}

export enum SERVICE_TYPE {
    DIRECT_SERVICE = 'DIRECT_SERVICE',
    REQUEST_SERVICE = 'BY_REQUEST_SERVICE'
}

export enum STAFF_STATUS {
    ACTIVE = 'ACTIVE',
    IN_ACTIVE = 'DISABLED',
}

export enum APPOINTMENT_TYPES {
    DIRECT_APPOINTMENT = 'DIRECT_APPOINTMENT',
    BY_REQUEST_APPOINTMENT = 'BY_REQUEST_APPOINTMENT'
}

export enum APPOINTMENT_STATUS {
    UNSCHEDULED = 'UNSCHEDULED',
    SCHEDULED = 'SCHEDULED',
    CONFIRMED = 'CONFIRMED',
    CANCELLED = 'CANCELLED',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETE = 'COMPLETE',
    MISSED = 'MISSED'
}

export enum AUTHOR_TYPES {
    TRANSCRIBER = 'TRANSCRIBER',
    STAFF_MEMBER = 'STAFF_MEMBER'
}

export enum PACKAGE_STATUS {
    RESERVED = 'RESERVED',
    ACTIVE = 'ACTIVE',
    IN_ACTIVE = 'IN_ACTIVE',
    ALL = 'ALL'
}

export enum PATIENT_AGE_RULES {
    BOTH = 'ALL',
    BELOW_18 = 'BELOW_18_ONLY',
    ABOVE_18 = 'ABOVE_18_ONLY'
}

export const LANGUAGES = ['ENGLISH', 'SPANISH', 'AMHARIC', 'ARABIC', 'ARMENIAN', 'BENGALI', 'CHINESE',
    'CAJUN', 'CROATIAN', 'CZECH', 'DANISH', 'DUTCH', 'FINNISH', 'FORMOSAN', 'FRENCH', 'FRENCH_CREOLE',
    'GERMAN', 'GREEK', 'GUJARATHI', 'HEBREW', 'HINDI_URDU', 'HUNGARIAN', 'ILOCANO', 'ITALIAN', 'JAPANESE',
    'KOREAN', 'KRU', 'LITHUANIAN', 'MALAYALAM', 'MIAO_HMONG', 'MON_KHMER_CAMBODIAN', 'NAVAHO', 'NORWEGIAN',
    'PANJABI', 'PERSIAN', 'PENNSYLVANIA_DUTCH', 'POLISH', 'PORTUGUESE', 'RUMANIAN', 'RUSSIAN', 'SAMOAN',
    'SERBOCROATIAN', 'SLOVAK', 'SWEDISH', 'SYRIAC', 'TAGALOG', 'THAI_LAOTIAN', 'TURKISH', 'UKRAINIAN',
    'VIETNAMESE', 'YIDDISH'];